export default {
    ACTION_CHANGE_ORDER: 'ACTION_CHANGE_ORDER',
    ACTION_ADD_TASK: 'ACTION_ADD_TASK',
    ACTION_UPDATE_TASK: 'ACTION_UPDATE_TASK',
    ACTION_REMOVE_TASK: 'ACTION_REMOVE_TASK',
    ACTION_LOAD_TASKS: 'ACTION_LOAD_TASKS'
};